"""
This module uses repak.exe by trumank (https://github.com/trumank)
Licensed under MIT License and Apache License 2.0
"""
# modules/mod.py
import os
import subprocess
import shutil
from pathlib import Path
import sys
from tkinter import messagebox

class ModCreator:
    def __init__(self, base_path):
        self.base_path = base_path
        if getattr(sys, 'frozen', False):
            self.exe_dir = os.path.dirname(sys.executable)
        else:
            self.exe_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    def find_pak_files(self, directory):
        """Recursively find .pak files in directory and its subdirectories"""
        pak_files = []
        for root, _, files in os.walk(directory):
            for file in files:
                if file.endswith('.pak'):
                    pak_files.append(os.path.join(root, file))
        return pak_files

    def check_incompatible_mods(self, mods_path):
        """Check for incompatible mods in the mods directory and its subdirectories"""
        if not os.path.exists(mods_path):
            return
            
        incompatible_keywords = ['FluidMovementAim', 'FMAO']
        found_mods = []
        
        pak_files = self.find_pak_files(mods_path)
        for file_path in pak_files:
            filename = os.path.basename(file_path)
            if any(keyword in filename for keyword in incompatible_keywords):
                found_mods.append(filename)
                    
        if found_mods:
            message = ("It looks like you still have Fluid Movement Aiming Overhaul installed.\n\n"
                      "Please remove these mods before playing:\n"
                      f"{chr(10).join(found_mods)}\n\n"
                      "Good hunting, Stalker.")
            messagebox.showwarning("Incompatible Mods", message)

    def create_mod(self, config, mods_path):
        # Check for incompatible mods first
        self.check_incompatible_mods(mods_path)
        
        # Only look in the correct repak folder location
        repak_path = self._find_repak()
        if not repak_path:
            raise FileNotFoundError(
                "repak.exe not found!\n\n"
                "Please create a folder named 'repak' and place repak.exe inside it.\n"
                f"The repak folder should be at: {os.path.join(self.exe_dir, 'repak')}\n\n"
                "Folder structure should be:\n"
                "📁 Your Installation Folder\n"
                "   └─📄 Stalker Configurator Aiming Movement.exe\n"
                "   └─📁 repak\n"
                "      └─📄 repak.exe"
            )

        try:
            # Create mod only after confirming repak exists
            mod_path = Path('z_SCAMMovementAiming_P/Stalker2/Content/GameLite/GameData/ObjPrototypes')
            mod_path.mkdir(parents=True, exist_ok=True)
            
            if 'Aiming' in config:
                del config['Aiming']
            
            cfg_content = self._generate_cfg_content(config)
            
            with open(mod_path / 'zSCAM.cfg', 'w') as f:
                f.write(cfg_content)
            
            self._run_repak(mods_path, repak_path)
        except Exception as e:
            # Clean up any created folders if there's an error
            if os.path.exists('z_SCAMMovementAiming_P'):
                shutil.rmtree('z_SCAMMovementAiming_P')
            raise

    def _find_repak(self):
        """Find repak.exe in the correct location only"""
        # First check if it's bundled
        bundled_path = os.path.join(self.base_path, 'repak', 'repak.exe')
        if os.path.exists(bundled_path):
            return bundled_path

        # If not bundled, check next to the executable/script
        external_path = os.path.join(self.exe_dir, 'repak', 'repak.exe')
        if os.path.exists(external_path):
            return external_path

        return None

    def _generate_cfg_content(self, config):
        content = "CustomPlayer : struct.begin {refurl=../ObjPrototypes.cfg; refkey=Player}\n"
        for section, values in config.items():
            content += f"   {section} : struct.begin\n"
            for key, value in values.items():
                content += f"      {key} = {value}\n"
            content += "   struct.end\n"
        content += "struct.end\n\n"
        content += "// Generated by SCAM (Stalker Configurator Aiming & Movement) by v3fish"
        return content

    def _run_repak(self, mods_path, repak_path):
        try:
            subprocess.run([repak_path, 'pack', 'z_SCAMMovementAiming_P'], check=True)
            shutil.move('z_SCAMMovementAiming_P.pak', os.path.join(mods_path, 'z_SCAMMovementAiming_P.pak'))
            shutil.rmtree('z_SCAMMovementAiming_P')
        except subprocess.CalledProcessError as e:
            if os.path.exists('z_SCAMMovementAiming_P'):
                shutil.rmtree('z_SCAMMovementAiming_P')
            raise RuntimeError(f"Failed to run repak: {str(e)}")
        except Exception as e:
            if os.path.exists('z_SCAMMovementAiming_P'):
                shutil.rmtree('z_SCAMMovementAiming_P')
            raise RuntimeError(f"Error during mod creation: {str(e)}")